<<<<<<< HEAD
package com.haisa.entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final
=======
package com.haisa.Entity;

>>>>>>> af595be4425b9aef60319fd77a738c887e8df525

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

<<<<<<< HEAD
/**
 * GenreMovie generated by hbm2java
 */
@Entity
@Table(name = "GenreMovie", schema = "dbo", catalog = "MovieManagement")
public class GenreMovie implements java.io.Serializable {

	private Integer genreId;
	private Serializable name;
=======
@Entity
@Table(name = "GenreMovie", schema = "dbo", catalog = "MovieManagement")
public class GenreMovie   {

	private Integer genreId;
	private String name;
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525

	public GenreMovie() {
	}

<<<<<<< HEAD
	public GenreMovie(Serializable name) {
=======
	public GenreMovie(String name) {
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "genreId", unique = true, nullable = false)
	public Integer getGenreId() {
		return this.genreId;
	}

	public void setGenreId(Integer genreId) {
		this.genreId = genreId;
	}

	@Column(name = "name")
	public Serializable getName() {
		return this.name;
	}

<<<<<<< HEAD
	public void setName(Serializable name) {
=======
	public void setName(String name) {
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
		this.name = name;
	}

}
