<<<<<<< HEAD
package com.haisa.entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "Movie", schema = "dbo", catalog = "MovieManagement")
public class Movie implements java.io.Serializable {

	private Integer movieId;
	private Serializable movieName;
	private Integer duration;
	private Serializable description;
	private String thumbnail;
	private Serializable actors;
	private Serializable director;
	private Integer ageLimit;
	private Integer status;

	public Movie() {
	}

	public Movie(Serializable movieName, Integer duration, Serializable description, String thumbnail,
			Serializable actors, Serializable director, Integer ageLimit, Integer status) {
		this.movieName = movieName;
		this.duration = duration;
		this.description = description;
		this.thumbnail = thumbnail;
		this.actors = actors;
		this.director = director;
		this.ageLimit = ageLimit;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "movieId", unique = true, nullable = false)
	public Integer getMovieId() {
		return this.movieId;
=======
package com.haisa.Entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name ="movie")
public class Movie {
		
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="movieid")
    private Integer movieId;
    
    @Column(name = "moviename")
    private String movieName;
    
    @Column(name="duration")
    private String duration;
    
    @Column(name="description")
    private String description;
    
    @Column(name="thumbnail")
    private String thumbnail;
    
    @Column(name="actors")
    private String actors;
    
    @Column(name="director")
    private String director;
    
    @Column(name = "agelimit")
    private Integer ageLimit;
    
    @Column(name="status")
    private Integer status;

    
	public Integer getMovieId() {
		return movieId;
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	}

	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

<<<<<<< HEAD
	@Column(name = "movieName")
	public Serializable getMovieName() {
		return this.movieName;
	}

	public void setMovieName(Serializable movieName) {
		this.movieName = movieName;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "thumbnail")
	public String getThumbnail() {
		return this.thumbnail;
=======
	public String getMovieName() {
		return movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getThumbnail() {
		return thumbnail;
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

<<<<<<< HEAD
	@Column(name = "actors")
	public Serializable getActors() {
		return this.actors;
	}

	public void setActors(Serializable actors) {
		this.actors = actors;
	}

	@Column(name = "director")
	public Serializable getDirector() {
		return this.director;
	}

	public void setDirector(Serializable director) {
		this.director = director;
	}

	@Column(name = "ageLimit")
	public Integer getAgeLimit() {
		return this.ageLimit;
=======
	public String getActors() {
		return actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public Integer getAgeLimit() {
		return ageLimit;
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	}

	public void setAgeLimit(Integer ageLimit) {
		this.ageLimit = ageLimit;
	}

<<<<<<< HEAD
	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
=======
	public Integer getStatus() {
		return status;
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
<<<<<<< HEAD

=======
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
}
