<<<<<<< HEAD
package com.haisa.entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final
=======
package com.haisa.Entity;

>>>>>>> af595be4425b9aef60319fd77a738c887e8df525

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

<<<<<<< HEAD
/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "Room", schema = "dbo", catalog = "MovieManagement")
public class Room implements java.io.Serializable {
=======

@Entity
@Table(name = "room")
public class Room {
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525

	private Integer roomId;
	private Integer roomName;
	private Integer seatAmount;
	private Integer cinemaId;

	public Room() {
	}

	public Room(Integer roomName, Integer seatAmount, Integer cinemaId) {
		this.roomName = roomName;
		this.seatAmount = seatAmount;
		this.cinemaId = cinemaId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

<<<<<<< HEAD
	@Column(name = "roomID", unique = true, nullable = false)
=======
	@Column(name = "roomid")
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

<<<<<<< HEAD
	@Column(name = "roomName")
=======
	@Column(name = "roomname")
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	public Integer getRoomName() {
		return this.roomName;
	}

	public void setRoomName(Integer roomName) {
		this.roomName = roomName;
	}

<<<<<<< HEAD
	@Column(name = "seatAmount")
=======
	@Column(name = "seatamount")
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	public Integer getSeatAmount() {
		return this.seatAmount;
	}

	public void setSeatAmount(Integer seatAmount) {
		this.seatAmount = seatAmount;
	}

<<<<<<< HEAD
	@Column(name = "cinemaId")
=======
	@Column(name = "cinemaid")
>>>>>>> af595be4425b9aef60319fd77a738c887e8df525
	public Integer getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Integer cinemaId) {
		this.cinemaId = cinemaId;
	}

}
